Refresh reflections of one dataset through disable and enable flag
rymurr/dremio_client pull request #68
Opened 2020-05-09 18:18 UTC by viktordremio

2020-05-09 18:19 UTC, viktordremio commented
1. added a feature to refresh reflection through reflection api by disabling and enabling of reflection
2. set some methods from public to private in .util.refrsh.py

2020-05-11 12:07 UTC, rymurr requested changes
Not a huge fan of adding this method however its a common pattern. Small pieces of feedback though,

2020-05-11 12:07 UTC, rymurr commented on dremio_client/util/refresh.py
> +def _reenable_reflection(client, refl_json):
This should be two methods 'enable' and 'disable' reflection

2020-05-11 12:07 UTC, rymurr commented on dremio_client/dremio_simple_client.py
> +    def refresh_reflections_of_one_dataset(self, path):
This is a potentially destructive operation as it temporarily removes a reflection causing a fair chunk of work do be done and slowing down queries in the meantime. I think it should have a [big warning](https://pythonhosted.org/an_example_pypi_project/sphinx.html#paragraph-markup) in the pydoc and perhaps a `logging.warn` when the method is called.

2020-05-20 08:42 UTC, merged